name: build-yt6801-ko
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git dkms curl

      - name: Install Proxmox headers (6.14.8-2-pve)
        run: |
          curl -O http://download.proxmox.com/debian/pve/dists/trixie/pve-no-subscription/binary-amd64/pve-headers-6.14.8-2-pve_6.14.8-2_amd64.deb
          sudo apt install -y ./pve-headers-6.14.8-2-pve_6.14.8-2_amd64.deb

      - name: Build yt6801 kernel module
        run: |
          cd src || cd .
          make -C /lib/modules/6.14.8-2-pve/build M="$PWD" modules
          mkdir -p build-output
          find . -name "yt6801.ko" -exec cp {} build-output/ \;

      - name: Upload built module
        uses: actions/upload-artifact@v4
        with:
          name: yt6801-ko
          path: build-output/yt6801.ko
