name: build yt6801 .deb

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
  workflow_call: {}

jobs:
  build-deb:
    runs-on: ubuntu-latest
    env:
      DEB_PACKAGE_NAME: yt6801-driver
      KERNEL_VERSIONS: "6.14.8-2-pve 6.14.11-4-pve 6.12.43+deb13-amd64"
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install build deps
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential dkms debhelper dh-make fakeroot git

    # VOLITELNÉ: pokud máš konkrétní proxmox header package URL, můžeš ho sem stáhnout.
    # Nechávám volné, aby stroj zkusil dostupné linux-headers; pokud to selže, bude potřeba
    # nahrát headers do repozitáře nebo přidat dalších krok pro stažení proxmox headers.

    - name: Prepare deb structure
      run: |
        mkdir -p package/usr/src/yt6801
        cp -r ./* package/usr/src/yt6801
        pushd package
        mkdir -p DEBIAN
        cat > DEBIAN/control <<'EOF'
Package: ${DEB_PACKAGE_NAME}
Version: 1.0
Section: kernel
Priority: optional
Architecture: amd64
Maintainer: You <you@example.com>
Description: yt6801 kernel driver (source packaged). Build and install module for target kernel.
EOF
        popd

    - name: Build .deb (source-only; module build done on target)
      run: |
        dpkg-deb --build package
        mv package.deb yt6801-source-package.deb || true
        ls -lh

    - name: Upload artifact (.deb)
      uses: actions/upload-artifact@v4
      with:
        name: yt6801-source-deb
        path: yt6801-source-package.deb
