name: build-yt6801-ko
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout yt6801 source
        uses: actions/checkout@v4

      # ŽÁDNÉ apt-get update / žádné zdroje! Jen dpkg z lokálních .deb
      - name: Install Proxmox headers 6.14.8-2-pve (no APT)
        run: |
          set -euxo pipefail
          KVER="6.14.8-2-pve"
          cd /tmp
          # stáhni přesné headery pro 6.14.8-2
          curl -fLO "http://download.proxmox.com/debian/pve/pool/pve-kernel/proxmox-headers-6.14_6.14.8-2_all.deb"
          # druhý balík má různé názvy; zkus varianty
          curl -fLO "http://download.proxmox.com/debian/pve/pool/pve-kernel/pve-headers_${KVER}_6.14.8-2_amd64.deb" \
          || curl -fLO "http://download.proxmox.com/debian/pve/pool/pve-kernel/linux-headers-${KVER}_6.14.8-2_amd64.deb"

          # nainstaluj lokálně (bez apt)
          sudo dpkg -i /tmp/proxmox-headers-6.14_6.14.8-2_all.deb /tmp/*headers*${KVER}*_amd64.deb

          # symlink pro build systém
          sudo mkdir -p "/lib/modules/${KVER}"
          if [ ! -e "/lib/modules/${KVER}/build" ]; then
            sudo ln -s "/usr/src/linux-headers-${KVER}" "/lib/modules/${KVER}/build"
          fi
          ls -l "/lib/modules/${KVER}/build"

      - name: Build yt6801.ko against 6.14.8-2-pve
        run: |
          set -euxo pipefail
          KVER="6.14.8-2-pve"
          cd src
          make -C "/lib/modules/${KVER}/build" M="$PWD" clean modules
          mkdir -p build-output
          cp -v yt6801.ko build-output/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: yt6801-ko-6.14.8-2-pve
          path: build-output/yt6801.ko
