name: build yt6801 .deb

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper fakeroot rsync

      - name: Prepare deb structure
        run: |
          set -e
          mkdir -p pkg/usr/src/yt6801
          rsync -a --exclude ".git" --exclude ".github" ./ pkg/usr/src/yt6801/
          mkdir -p pkg/DEBIAN
          cat > pkg/DEBIAN/control <<'EOF'
Package: yt6801-source
Version: 1.0
Section: kernel
Priority: optional
Architecture: amd64
Maintainer: Your Name <you@example.com>
Description: YT6801 Ethernet driver (source only). Build the kernel module on the target with matching headers.
EOF

      - name: Build .deb
        run: |
          dpkg-deb --build pkg yt6801-source.deb
          ls -lh yt6801-source.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: yt6801-source-deb
          path: yt6801-source.deb
